// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Home", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("MaxDevices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("MaxDevices");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Homes", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("bytea")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("Email");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("EmailHash");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("EmailVerified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PhoneNumber");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EmailHash");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Identity.Domain.Entities.Home", b =>
                {
                    b.OwnsMany("Identity.Domain.Entities.HomeMembership", "Members", b1 =>
                        {
                            b1.Property<byte[]>("Id")
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("HomeId")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("JoinedAt");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("Role");

                            b1.Property<byte[]>("UserId")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.HasKey("Id");

                            b1.HasIndex("HomeId");

                            b1.ToTable("HomeMemberships", "identity");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Identity.Domain.Entities.User", b =>
                {
                    b.OwnsMany("Identity.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<byte[]>("Id")
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("UserId")
                                .HasColumnType("bytea");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("Id", "UserId");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("IX_RefreshTokens_UserId");

                            b1.ToTable("RefreshTokens", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Identity.Domain.Entities.Session", "Sessions", b1 =>
                        {
                            b1.Property<byte[]>("Id")
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("UserId")
                                .HasColumnType("bytea");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeviceFingerprint")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)");

                            b1.Property<bool>("IsTrusted")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("UserAgent")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("Id", "UserId");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("IX_Sessions_UserId");

                            b1.ToTable("Sessions", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Identity.Domain.Entities.TrustedDevice", "TrustedDevices", b1 =>
                        {
                            b1.Property<byte[]>("Id")
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("UserId")
                                .HasColumnType("bytea");

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("DeviceFingerprint")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("Id", "UserId");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("IX_TrustedDevices_UserId");

                            b1.ToTable("TrustedDevices", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");

                    b.Navigation("TrustedDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
